#!/bin/bash

DOCKER_IMAGE=localhost:5000/mt0erfztxt/pod-commander-demo:latest

(cd .. && lein do clean, uberjar && cp target/uberjar/pod-commander-demo.jar demo/pod-commander-demo.jar)

eval $(minikube docker-env)
docker build -t $DOCKER_IMAGE .
docker push $DOCKER_IMAGE
