---
apiVersion: v1
kind: Pod
metadata:
  namespace: demo
  name: executor
spec:
  containers:
    - image: busybox
      name: c01
      args:
        - "/bin/sh"
        - "-c"
        - "while true; do echo c01 `date '+%Y-%m-%d %H:%M:%S'`; ls -la /tmp; echo ''; sleep 5; done"
    - image: busybox
      name: c02
      args:
        - "/bin/sh"
        - "-c"
        - "while true; do echo c02 `date '+%Y-%m-%d %H:%M:%S'`; ls -la /tmp; echo ''; sleep 5; done"
