---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: demo
  name: demouser
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["deployments", "replicasets", "pods", "pods/attach", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
