---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: demo
  name: demouser
subjects:
  - kind: User
    name: demouser
    apiGroup: ""
roleRef:
  kind: Role
  name: demouser
  apiGroup: ""
